services:
  ros2_humble:
    build: .
    container_name: ros2_dev_env
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - MQTT_BROKER_HOST=www.waddoc.site
      - MQTT_BROKER_PORT=443
      - MQTT_WS_PATH=/mqtt
      - VEHICLE_ID=${VEHICLE_ID:-vehicle-01}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./workspace:/root/workspace:rw
    command: tail -f /dev/null
    depends_on:
      - mediamtx
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu, video, compute, utility ]

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx_server
    network_mode: "host"
    environment:
      - MTX_WEBRTCICEUDP=yes
      - MTX_WEBRTCICEHOSTSNAT1TO1=100.89.189.27
    restart: unless-stopped
