services:
  # 1. EC2 제노 브릿지
  zenoh_bridge_ec2:
    image: eclipse/zenoh-bridge-ros2dds:1.7.2
    container_name: zenoh_bridge_ec2
    network_mode: "host"
    environment:
      - ROS_DISTRO=humble  # <== 이 줄을 반드시 추가하십시오!
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=<CycloneDDS><Domain><General><NetworkInterfaceAddress>lo</NetworkInterfaceAddress></General></Domain></CycloneDDS>
    command: [ "-l", "tcp/0.0.0.0:8081" ]
    restart: unless-stopped

  # 2. EC2 파이썬 앱
  ros2_app_ec2:
    build:
      context: ./router_app
      dockerfile: Dockerfile
    container_name: ros2_app_ec2
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - PYTHONUNBUFFERED=1
      # DDS 통신을 강제로 루프백(lo) 인터페이스에 묶습니다.
      - CYCLONEDDS_URI=<CycloneDDS><Domain><General><NetworkInterfaceAddress>lo</NetworkInterfaceAddress></General></Domain></CycloneDDS>
    depends_on:
      - zenoh_bridge_ec2
    restart: unless-stopped
    
  
