services:
  # === Reverse Proxy ===
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-api
      - frontend
      - livekit
    networks:
      - waddoc-net

  # === Frontend ===
  frontend:
    build: ../src/FE
    expose:
      - "3000"
    networks:
      - waddoc-net

  # === Backend ===
  spring-api:
    build: ../src/BE
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - LIVEKIT_HOST=http://livekit:7880
      - AI_IDV_URL=https://${DEV_GPU_SERVER_HOST}/idv/api/v1/verify
      - AI_TRIAGE_URL=https://${DEV_GPU_SERVER_HOST}/triage/api/v1/recommend
      - FILE_STORAGE_ROOT=/data/uploads
      - AI_IDV_TRANSFER_MODE=multipart
      - APP_SEED_ENABLED=${APP_SEED_ENABLED:-true}
      - APP_SEED_DEFAULT_PASSWORD=${APP_SEED_DEFAULT_PASSWORD:-Passw0rd!}
    volumes:
      - ./local-storage/uploads:/data/uploads
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - waddoc-net

  # === Database ===
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: waddoc
      POSTGRES_USER: waddoc
      POSTGRES_PASSWORD: waddoc_dev
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      # 추후 배포할떄는 expose로 변경
      - "5432:5432"
    networks:
      - waddoc-net

  # === Cache ===
  redis:
    image: redis:7-alpine
    command: redis-server --notify-keyspace-events Ex
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - waddoc-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - waddoc-net

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    depends_on:
      - zookeeper
    networks:
      - waddoc-net

  # === WebRTC ===
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "3478:3478/udp"
    environment:
      LIVEKIT_KEYS: "devkey: devsecret"
    networks:
      - waddoc-net

volumes:
  pg_data:
  redis_data:


networks:
  waddoc-net:
    driver: bridge
