port: 7880
rtc:
  use_external_ip: true
  udp_port: 8882
  tcp_port: 8881
turn:
  enabled: true
  domain: turn.waddoc.site
  tls_port: 0
  udp_port: 8478
  relay_range_start: 8600
  relay_range_end: 8699
