port: 7880
rtc:
  use_external_ip: false
  udp_port: 8882
  tcp_port: 8881
  turn_servers:
    - host: $LIVEKIT_NODE_IP
      port: 8478
      protocol: udp
      username: waddoc
      credential: $TURN_SECRET
turn:
  enabled: false
